name: Render Jupyter Notebooks

on: [push]  # Trigger the workflow on push events

jobs:
  render-notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jupyter/render-notebooks@v1
        with:
          output_dir: output  # Directory to store rendered notebooks
